import { NextRequest, NextResponse } from "next/server";
import { verifyPrivyToken } from "@/lib/privy/server";
import { createAdminClient } from "@/lib/supabase/admin";

/**
 * S4-T03 + S4-T05: exchange a Privy access token for the user's mcpxgg
 * account. Verifies the token server-side, ensures a users row exists,
 * binds the derived Sui address + privy_did, and returns the API key
 * (auto-generated by the users table default on first insert).
 *
 * Postgres stays a mirror — the only identity facts written here are
 * sui_address / privy_did / migration_status (ADR-011).
 */

export async function POST(req: NextRequest) {
  const authz = req.headers.get("authorization") ?? "";
  const token = authz.toLowerCase().startsWith("bearer ")
    ? authz.slice(7).trim()
    : "";
  if (!token) {
    return NextResponse.json({ error: "missing bearer token" }, { status: 401 });
  }

  let identity;
  try {
    identity = await verifyPrivyToken(token);
  } catch {
    return NextResponse.json({ error: "invalid privy token" }, { status: 401 });
  }

  const sb = createAdminClient();
  const email =
    identity.email ?? `${identity.privyDid.replace(/[^a-z0-9]/gi, "_")}@privy.mcpx.gg`;

  // Find existing user by privy_did, then by email.
  const existing = (await sb
    .from("users")
    .select("id, api_key")
    .or(`privy_did.eq.${identity.privyDid},email.eq.${email}`)
    .maybeSingle()) as { data: { id: string; api_key: string } | null };

  let userId = existing.data?.id ?? null;

  if (!userId) {
    // Create the auth user; the handle_new_user() trigger inserts the
    // matching public.users row (with a generated api_key).
    const created = await sb.auth.admin.createUser({
      email,
      email_confirm: true,
    });
    if (created.error || !created.data.user) {
      return NextResponse.json(
        { error: `account create failed: ${created.error?.message ?? "unknown"}` },
        { status: 500 },
      );
    }
    userId = created.data.user.id;
  }

  const migrationStatus = identity.suiAddress ? "migrated" : "migrating";
  const { error: updErr } = await sb
    .from("users")
    .update({
      privy_did: identity.privyDid,
      sui_address: identity.suiAddress,
      migration_status: migrationStatus,
    })
    .eq("id", userId);
  if (updErr) {
    return NextResponse.json({ error: updErr.message }, { status: 500 });
  }

  const { data: row } = (await sb
    .from("users")
    .select("api_key")
    .eq("id", userId)
    .single()) as { data: { api_key: string } | null };

  return NextResponse.json({
    apiKey: row?.api_key ?? null,
    suiAddress: identity.suiAddress,
    migrationStatus,
  });
}
